# Generated by Django 4.2.5 on 2023-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('specialty', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='doctor')),
            ],
        ),
    ]
